source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'
gem 'watir-webdriver'
gem 'rake'
gem 'parallel_tests'
# gem to connect to saucelabs and also dynamically change browser parameters
gem 'saucelabs'
gem 'dbi'
gem 'ruby-odbc'
gem 'geckodriver-helper'

