require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.profile = 'default'
  t.cucumber_opts = '--tags @Smoke'
  t.cucumber_opts = "--format pretty"
end

task :default => :features